trigger:
- master

resources:
  repositories:
    - repository: templates
      type: GitHub
      name: divvun/divvun-ci-config
      endpoint: divvun-ci

jobs:
  - template: repo/templates/keyboards.yml@templates
    parameters:
      name: crk
      packageName: keyboard-crk
      kbdgenFolder: "crk.kbdgen"
      repositoryWin: "https://pahkat.uit.no/repo/windows"
      repositoryMac: "https://pahkat.uit.no/repo/macos"
      languages:
        - projectjjName: giella-crk
          path: usr/share/giella/mobilespellers/crk-mobile.zhfst
          name: crk
