template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 3
template_sha = "bad9d2392ecf1eef72070ce143897338af2dca62"

[replacements]
__UND2C__ = "crk"
__UNDEFINED__ = "Plains Cree"
__UND__ = "crk"
